const newsResponse = [
  {
    NewsID: 81770,
    Source: "RotoBaller",
    Updated: "2022-02-11T00:48:28",
    TimeAgo: "3 hours ago",
    Title: "Rudy Gobert Earns Questionable Tag For Friday",
    Content:
      "Utah Jazz center Rudy  Gobert (calf) has been deemed questionable to suit up for Friday's game vs. Orlando as he works his way back from a strained left calf. The league's leading rebounder has missed each of Utah's past eight games, paving the way for Hassan  Whiteside to claim elevated DFS appeal and short-term season-long viability. Prior to going down with the injury, Gobert had reeled off a double-double in 18 of his last 19 appearances, shooting a whopping 68.5 percent overall in that span. His previous meeting with the Magic back on Nov. 7 saw him log 21 points, 15 boards, and four blocks, elevating his appeal if he is ultimately cleared.",
    Url: "https://www.rotoballer.com/player-news/rudy-gobert-earns-questionable-tag-for-friday/992776",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries, Lineup, Matchup-Outlook",
    PlayerID: 20000840,
    TeamID: 17,
    Team: "UTA",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "NBA Injury Report",
    OriginalSourceUrl:
      "https://ak-static.cms.nba.com/referee/injury/Injury-Report_2022-02-10_07PM.pdf",
  },
  {
    NewsID: 81732,
    Source: "RotoBaller",
    Updated: "2022-02-10T02:12:16",
    TimeAgo: "18 hours ago",
    Title: "Domantas Sabonis Cleared On Wednesday",
    Content:
      "Sacramento Kings forward Domantas  Sabonis has been cleared to play in Wednesday's game against the Minnesota Timberwolves. Also, Jeremy  Lamb and Justin  Holiday are available for Wednesday's contest as well. All three former Pacers are eligible to make their team debut now. It's assumed that they would suit up here, but the team hasn't officially announced that. Fantasy managers will have to wait until closer to tip-off before putting Sabonis back in their lineups.",
    Url: "https://www.rotoballer.com/player-news/domantas-sabonis-cleared-on-wednesday/992569",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Sit-Start",
    PlayerID: 20001683,
    TeamID: 30,
    Team: "SAC",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Sean Cunningham",
    OriginalSourceUrl:
      "https://twitter.com/SeanCunningham/status/1491593502072791040",
  },
  {
    NewsID: 81702,
    Source: "RotoBaller",
    Updated: "2022-02-09T00:01:35",
    TimeAgo: "yesterday",
    Title: "Maxi Kleber Set To Return On Tuesday",
    Content:
      "Dallas Mavericks forward Maxi  Kleber (knee) will be available for Tuesday's game against the Detroit Pistons, according to Mavericks head coach Jason Kidd. Kleber sat out each of the team's last two games due to a left knee injury. Reggie  Bullock entered the starting lineup while Kleber was sidelined and played well. Bullock should continue to see significant minutes off the bench, despite Kleber's return. The last time we saw Kleber last Wednesday, he put together one of his best games all season as he racked up 10 points, eight rebounds, four blocks, three steals and two three-pointers.",
    Url: "https://www.rotoballer.com/player-news/maxi-kleber-set-to-return-on-tuesday/992202",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries",
    PlayerID: 20001909,
    TeamID: 25,
    Team: "DAL",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Chuck Cooperstein",
    OriginalSourceUrl:
      "https://twitter.com/coopmavs/status/1491198076044087296",
  },
  {
    NewsID: 81674,
    Source: "RotoBaller",
    Updated: "2022-02-08T00:01:23",
    TimeAgo: "2 days ago",
    Title: "Golden State Increases Klay Thompson’s Minutes Limit",
    Content:
      "Golden State Warriors shooting guard Klay  Thompson has had his playing time cap elevated to 30 minutes ahead of Monday's game against Oklahoma City. Thompson has scored in double figures in each of his 11 appearances this season, averaging 16.3 points and 2.8 made triples per contest. It remains unlikely that the Warriors will thrust Thompson into back-to-backs for the time being, but he stands to continue serving as a significant asset in the DFS market when cleared. With the Thunder allowing the fourth-most three-point attempts (38.5) of any team in the league during 2021-22, Thompson's elevated DFS appeal begins Monday.",
    Url: "https://www.rotoballer.com/player-news/golden-state-increases-klay-thompsons-minutes-limit/991905",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Lineup, Matchup-Outlook",
    PlayerID: 20000486,
    TeamID: 26,
    Team: "GS",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Evan Webeck",
    OriginalSourceUrl:
      "https://twitter.com/EvanWebeck/status/1490832066837102593",
  },
  {
    NewsID: 81658,
    Source: "RotoBaller",
    Updated: "2022-02-07T02:09:16",
    TimeAgo: "3 days ago",
    Title: "Larry Nance Jr. Suffers Setback In Recovery",
    Content:
      "Portland Trail Blazers forward Larry  Nance  Jr. (knee) has suffered a setback in his recovery, according to head coach Chauncey Billups. Nance has not appeared in a game since early January and doesn't have a timetable for his return. Billups announced recently that Nance suffered a setback and will be re-evaluated at some point. That is not an encouraging sign from a team that is short on forwards. Justise  Winslow, Trendon  Watford, and Greg  Brown  III should get plenty of chances in the second half of the season. Winslow has the highest upside of the three, but none of them are trustworthy fantasy assets right now.",
    Url: "https://www.rotoballer.com/player-news/larry-nance-jr-suffers-setback-in-recovery/991723",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries",
    PlayerID: 20001457,
    TeamID: 19,
    Team: "POR",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Jay Allen",
    OriginalSourceUrl: "https://twitter.com/PDXjay/status/1489796110210064388",
  },
  {
    NewsID: 81629,
    Source: "RotoBaller",
    Updated: "2022-02-06T02:54:09",
    TimeAgo: "4 days ago",
    Title: "De'Aaron Fox Out On Saturday",
    Content:
      "Sacramento Kings guard De'Aaron  Fox (ankle) won't play on Saturday versus the Thunder. Fox will now miss his eighth straight game because of left ankle soreness, so Davion  Mitchell and Tyrese  Haliburton should continue to handle most of the work out of the backcourt. Both men should be strongly considered for DFS contests as well as starting in all seasonal formats.",
    Url: "https://www.rotoballer.com/player-news/deaaron-fox-out-on-saturday/991448",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries, Top-Headlines",
    PlayerID: 20001824,
    TeamID: 30,
    Team: "SAC",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Sean Cunningham",
    OriginalSourceUrl:
      "https://twitter.com/SeanCunningham/status/1490151334783291393?s=20&amp;t=-XY7rpDl7wv3zz-gq0Of5w",
  },
  {
    NewsID: 81603,
    Source: "RotoBaller",
    Updated: "2022-02-05T02:10:56",
    TimeAgo: "5 days ago",
    Title: "Joe Harris May Require Second Ankle Surgery",
    Content:
      "Brooklyn Nets shooting guard Joe  Harris (ankle) may need to undergo a second surgery on his left ankle, according to his agent, Mark Bartelstein. The decision will be factored on the progress that Harris is able to make over the next couple of weeks. Harris has suffered a setback after his initial ankle surgery in November, making the elite three-point shooter a long-term stash in standard fantasy formats as there is some hope that he is able to make a return late in the season.",
    Url: "https://www.rotoballer.com/player-news/joe-harris-may-require-second-ankle-surgery/991259",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries",
    PlayerID: 20000584,
    TeamID: 8,
    Team: "BKN",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Adrian Wojnarowski - ESPN.com",
    OriginalSourceUrl:
      "https://www.espn.com/nba/story/_/id/33211223/brooklyn-nets-joe-harris-need-second-surgery-left-ankle-agent-says",
  },
  {
    NewsID: 81578,
    Source: "RotoBaller",
    Updated: "2022-02-04T02:09:22",
    TimeAgo: "6 days ago",
    Title: "LeBron James Won't Play Against Clippers",
    Content:
      "Los Angeles Lakers forward LeBron  James (knee) has been ruled out for Thursday's game against the Los Angeles Clippers. It was highly unlikely that James was going to play in this game. His timetable remains unknown and there's a chance that James sits out until the All-Star break. In the meantime, Anthony  Davis and Russell  Westbrook will continue to see a spike in usage. Malik  Monk (groin) and Carmelo  Anthony will see a boost in fantasy value as well with James sidelined. Monk is the better fantasy option between the two.",
    Url: "https://www.rotoballer.com/player-news/lebron-james-wont-play-against-clippers/990993",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries",
    PlayerID: 20000571,
    TeamID: 27,
    Team: "LAL",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Jovan Buha",
    OriginalSourceUrl:
      "https://twitter.com/jovanbuha/status/1489412068893618180?s=20&amp;t=aPtS6N5KXUJK2OuVB5r3Cg",
  },
  {
    NewsID: 81549,
    Source: "RotoBaller",
    Updated: "2022-02-03T02:18:15",
    TimeAgo: "7 days ago",
    Title: "Nikola Jokic Out On Wednesday",
    Content:
      "Denver Nuggets center Nikola  Jokic (toe) has been ruled out for Wednesday's game against the Utah Jazz. The Nuggets have decided to rest the reigning MVP against the beat up Jazz roster. Udoka  Azubuike is starting at center for Utah, so they decided to be cautious with Jokic. DeMarcus  Cousins (foot) is sidelined as well, so JaMychal  Green is the only active center left on the roster. He should see all the minutes he can handle on Wednesday. He'll be a decent streaming option and a possible DFS candidate for Wednesday's slate.",
    Url: "https://www.rotoballer.com/player-news/nikola-jokic-out-on-wednesday/990778",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries",
    PlayerID: 20001441,
    TeamID: 20,
    Team: "DEN",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Mike Singer",
    OriginalSourceUrl: "https://twitter.com/msinger/status/1489054630860390401",
  },
  {
    NewsID: 81529,
    Source: "RotoBaller",
    Updated: "2022-02-02T02:10:41",
    TimeAgo: "8 days ago",
    Title: "James Harden Officially Cleared To Play On Tuesday",
    Content:
      "Brooklyn Nets guard James  Harden (hand) has been cleared to play in Tuesday's game against the Phoenix Suns. He will return to the court here after a two-game absence. Hopefully, the right hand issue is behind him, so Harden's production won't be impacted by it. DeAndre'  Bembry should head to the second unit with Cam  Thomas losing playing time. Bruce  Brown won't have as big of a role with Harden returning. Fantasy managers should make sure Harden is back in their lineups for Tuesday's slate.",
    Url: "https://www.rotoballer.com/player-news/james-harden-officially-cleared-to-play-on-tuesday/990548",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries",
    PlayerID: 20000544,
    TeamID: 8,
    Team: "BKN",
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: "Marc Stein",
    OriginalSourceUrl:
      "https://twitter.com/TheSteinLine/status/1488685210585776134",
  },
  {
    NewsID: 81521,
    Source: "RotoBaller",
    Updated: "2022-02-01T20:46:09",
    TimeAgo: "9 days ago",
    Title: "Otto Porter Jr., Nemanja Bjelica Will Miss Tuesday’s Game",
    Content:
      "Golden State Warriors small/power forward Otto  Porter  Jr. (rest) and power forward/center Nemanja  Bjelica (back) have been ruled out for Tuesday's contest vs. the Spurs. Golden State is set to be extremely shorthanded for the outing with Stephen  Curry (toe), Klay  Thompson (rest), Draymond  Green (back), and others all ruled out. The loss of Porter and Bjelica on the wing means that Jonathan  Kuminga, Damion  Lee, and Moses  Moody are all in DFS sweet spots based on their price tag; additionally, any healthy Warriors guards will have significant upside as well. The next chance for Porter or Bjelica to return to action comes Thursday against Sacramento.",
    Url: "https://www.rotoballer.com/player-news/otto-porter-jr-nemanja-bjelica-will-miss-tuesdays-game/990491",
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: "Staff",
    Categories: "Injuries, Lineup, Matchup-Outlook, Sit-Start",
    PlayerID: 20000443,
    TeamID: 26,
    Team: "GS",
    PlayerID2: 20001429,
    TeamID2: 26,
    Team2: "GS",
    OriginalSource: "Connor Letourneau",
    OriginalSourceUrl:
      "https://twitter.com/Con_Chron/status/1488598207630356481",
  },
];

export default newsResponse;
